services:
  # PostgreSQL Database
  - type: pserv
    name: wallet-db
    plan: free
    region: oregon
    databaseName: wallet_db
    databaseUser: wallet_user

  # NestJS Application
  - type: web
    name: wallet-service
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build && npm run migration:run
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: wallet-db
          property: connectionString
      - key: RUN_MIGRATIONS
        value: 'true'
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_CALLBACK_URL
        value: https://wallet-service-1-5kml.onrender.com/wallet/paystack/webhook
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/docs
